In [2]:
import numpy as np

## Outline:
   - Operator Overloading
        - comparsion
        - String represenation

## Operator Overloading: Comparsion

### object equality

In [18]:
class Customer:
    def __init__(self, name, balance):
        self.name, self.balance = name, balance
cust1 = Customer("Muneed ul Hassan", 1000)
cust2 = Customer('Mehmood ul Hassan', 5000)
cust1 == cust2

False

In [19]:
class Customer:
    def __init__(self, name, balance):
        self.name, self.balance = name, balance
cust1 = Customer("Muneed ul Hassan", 1000)
cust2 = Customer("Muneed ul Hassan", 1000)
cust1 == cust2

False

In [20]:
print(cust1, cust2, sep='\n')

## custom comparsion

In [25]:
# two different array contain the same data

arr1 = np.array([1,2,3])
arr2 = np.array([1,2,3])

arr1 == arr2

array([ True,  True,  True])

In [ ]:
Over

## Overloading \__eq__()
- **\__ed__()** is called when 2 object od a same class are compared using **==**
- accept two argument, self and ither objects to be compare
- return boolean

In [49]:
class Customer:
    def __init__(self, ids, name):
        self.ids, self.name = ids, name 
        
    #will be called == is used
    def __eq__(self,other):
        #Diagnostic printout
        print("__eq__() is called..!!")
        
    # return True if all attributes match
        return (self.ids == other.ids) and \
            (self.name == other.name)

In [51]:
cust1 = Customer(123, "Muneed ul Hassan")
cust2 = Customer(123, "Muneed ul Hassan")

cust1 == cust2

__eq__() is called..!!


True

In [52]:
# Two unequal objects - different ids

customer1 = Customer(123,"Maryam Azar")
customer2 = Customer(456,"Maryam Azar")

customer1 == customer2

__eq__() is called..!!


False

<img src = "./media/comparsion.png">

\__hash__() to used object ad dictionary key and in sets

## Operator overloading: String represenation

### printing an object

In [1]:
class Customer:
    def __init__(self, name, balance):
        self.name, self.balance = name, balance

cust = Customer('Qasim Hassan', 5000)
print(cust)

In [3]:
arr = np.array([1,2,3,4])
print(arr)

[1 2 3 4]


**\__str__()**
- print(obj)
- str(obj)

In [4]:
print(np.array([1,2,3,4]))

[1 2 3 4]


In [5]:
str(np.array([1,2,3,4]))

'[1 2 3 4]'

- formal for end user
- **str**ing representation

**\__repr__()**

- repr(obj)
- printing on console

In [7]:
repr(np.array([1,2,3,4]))

'array([1, 2, 3, 4])'

In [8]:
np.array([1,2,3,4])

array([1, 2, 3, 4])

- formal, for developer
- **repr**oduceable **repr**esentation
- fallback for print()

### Implementation: str

In [12]:
class Customer:
    def __init__(self, name, balance):
        self.name, self.balance = name, balance
    
    def __str__(self):
        cust_str = """
        Customer:
        name : {name}
        balance: {balance}
        """.format(name= self.name,\
                   balance= self.balance)
        return cust_str

In [14]:
cust1 = Customer('Qasim Hassan', 3000)

# will implicitly call __str__()
print(cust1)


        Customer:
        name : Qasim Hassan
        balance: 3000
        


### Implementation: repr

In [17]:
class Customer:
    def __init__(self, name, balance):
        self.name, self.balance = name, balance
    
    def __repr__(self):
        #Notice the '---' around name
        return "Customer('{name}', {balance})".format(name= self.name, balance=self.balance)

cust = Customer('Qasim Hassan', 20000)
cust # <-- will implicity call __repr__()

Customer('Qasim Hassan', 20000)

Note: Suuround string argument with quotations marks in the **\__reper__()** output