## Comparsion Operators

### Numpy recap

In [1]:
# Code from Intro to Python for Data Science, Chapter 4
import numpy as np
np_height = np.array([1.73, 1.68, 1.71, 1.89, 1.79])
np_weight = np.array([65.4, 59.2, 63.6, 88.4, 68.7])
bmi = np_weight / np_height ** 2
bmi

array([21.85171573, 20.97505669, 21.75028214, 24.7473475 , 21.44127836])

In [2]:
bmi > 23

array([False, False, False,  True, False])

In [3]:
bmi[bmi > 23]

array([24.7473475])

### how Python values relate

#### Numeric comparsion

In [4]:
2<3

True

In [5]:
2==3

False

In [6]:
2<=3

True

In [7]:
2 >= 0.5

True

In [8]:
x= 4
y = 6

x > y

False

In [12]:
 3 < 4.1

True

#### string comparsion

In [9]:
"carl" < "chris"

True

In [10]:
'Qasim' < 'Hassan'

False

In [11]:
3 < "chris"

TypeError: '<' not supported between instances of 'int' and 'str'

<img src='./media/comparsion_operators.png'>

## Boolean Opearotrs
- and 
- or
- not
<img src = './media/truth_table.png'>

In [14]:
True and True

True

In [15]:
not True

False

In [16]:
False or True

True

In [17]:
x = 12
x > 5 and x < 15
# True     True

True

In [18]:
y = 5
y < 7 or y > 13
# True     False

True

### Implementation in NumPy

In [19]:
bmi

array([21.85171573, 20.97505669, 21.75028214, 24.7473475 , 21.44127836])

In [23]:
bmi > 21

array([ True, False,  True,  True,  True])

In [22]:
bmi < 22

array([ True,  True,  True, False,  True])

In [24]:
bmi > 21  and bmi < 22

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

Numpy have their own functions for and or not that are:
   - logical_and()
   - logical_or()
   - logical_not()

In [26]:
np.logical_and(bmi>21, bmi<22)

array([ True, False,  True, False,  True])

In [27]:
bmi[np.logical_and(bmi>21, bmi<22)]

array([21.85171573, 21.75028214, 21.44127836])

## Conditional Statements
- if else elif

#### if

In [33]:
num = 4
if num % 2 == 0: #True
    print('Even')

Even


In [32]:
num = 4
if num % 2 == 0: #True
    print('Multiplt lines can be added')
    print('Be careful about identation')
    print('Even')

Multiplt lines can be added
Be careful about identation
Even


In [35]:
num = 5 
if num % 2 == 0: #False
    print('Multiplt lines can be added')
    print('Be careful about identation')
    print('Even') # Nothing gona print if statment gonna false then comes else statemnet

#### else

In [36]:
z = 5
if z % 2 == 0 : # False
    print("z is even")
else :
    print("z is odd")

z is odd


#### elif

In [37]:
z = 3
if z % 2 == 0 :
    print("z is divisible by 2") # False
elif z % 3 == 0 :
    print("z is divisible by 3") # True
else :
    print("z is neither divisible by 2 nor by 3")

z is divisible by 3


In [38]:
z = 6
if z % 2 == 0 :
    print("z is divisible by 2") # True
elif z % 3 == 0 :
    print("z is divisible by 3") # Never reached
else :
    print("z is neither divisible by 2 nor by 3")

z is divisible by 2


## Filtering pandas DataFrames

In [42]:
import pandas as pd
brics = pd.read_csv("./bricks.csv", index_col = 0)
brics

country    capital    area  population
BR        Brazil   Brasilia   8.516      200.40
RU        Russia     Moscow  17.100      143.50
IN         India  New Delhi   3.286     1252.00
CH         China    Beijing   9.597     1357.00
SA  South Africa   Pretoria   1.221       52.98

#### Task: select countries with area over 8 million km2
we'll follow three steps:
- Select the area column
- Do comparison on area column
- Use result to select countries

##### step1 : Select the area column

In [43]:
brics["area"]

BR     8.516
RU    17.100
IN     3.286
CH     9.597
SA     1.221
Name: area, dtype: float64

###### Alternatives:
- brics.loc[:,'area']
- brics.iloc[:,2]

In [45]:
brics.loc[:,'area'] # another way  top get column

BR     8.516
RU    17.100
IN     3.286
CH     9.597
SA     1.221
Name: area, dtype: float64

In [47]:
brics.iloc[:,2] # another way to get column

BR     8.516
RU    17.100
IN     3.286
CH     9.597
SA     1.221
Name: area, dtype: float64

##### Step 2: Compare

In [48]:
brics["area"] > 8

BR     True
RU     True
IN    False
CH     True
SA    False
Name: area, dtype: bool

In [49]:
is_huge = brics["area"] > 8

##### Step 3: Subset DF

In [50]:
is_huge

BR     True
RU     True
IN    False
CH     True
SA    False
Name: area, dtype: bool

In [51]:
brics[is_huge]

country   capital    area  population
BR  Brazil  Brasilia   8.516       200.4
RU  Russia    Moscow  17.100       143.5
CH   China   Beijing   9.597      1357.0

###### Sumamry

In [52]:
#Method -1
is_huge = brics["area"] > 8
brics[is_huge]

country   capital    area  population
BR  Brazil  Brasilia   8.516       200.4
RU  Russia    Moscow  17.100       143.5
CH   China   Beijing   9.597      1357.0

In [53]:
#Method -2
brics[brics['area']>8]

country   capital    area  population
BR  Brazil  Brasilia   8.516       200.4
RU  Russia    Moscow  17.100       143.5
CH   China   Beijing   9.597      1357.0

###### Question: what if we have to check two conditions at a time 

In [54]:
np.logical_and(brics["area"] > 8, brics["area"] < 10)

BR     True
RU    False
IN    False
CH     True
SA    False
Name: area, dtype: bool

In [55]:
brics[np.logical_and(brics["area"] > 8, brics["area"] < 10)]

country   capital   area  population
BR  Brazil  Brasilia  8.516       200.4
CH   China   Beijing  9.597      1357.0

## Practice

#### equal to(==) and not equal to(!=)

In [56]:
print(2 == (1 + 1))
print("intermediate" != "python")
print(True != False)
print("Python" != "python")

True
True
True
True


In [58]:
# Comparison of booleans
print(True == False)

# Comparison of integers
print(-5*15 != 75)

# Comparison of strings
print("pyscript" == "PyScript")

# Compare a boolean with an integer
print(True == 1)

False
True
False
True


#### greater then(>) and less than (<)

In [60]:
print(3 < 4)
print(3 <= 4)
print("alpha" <= "beta")

True
True
True


In [59]:
# Comparison of integers
x = -3 * 6

# Comparison of strings
y = "test"

# Comparison of booleans
print(x >= -10)
print(y >= "test")
print( True > False)

False
True
True


#### Compare array

In [62]:
# Create arrays
import numpy as np
my_house = np.array([18.0, 20.0, 10.75, 9.50])
your_house = np.array([14.0, 24.0, 14.25, 9.0])

# my_house greater than or equal to 18
print(my_house >= 18 )

# my_house less than your_house
print(your_house > my_house)

[ True  True False False]
[False  True  True False]


#### and, or, not

In [64]:
# Define variables
my_kitchen = 18.0
your_kitchen = 14.0

# my_kitchen bigger than 10 and smaller than 18?
print(18 < my_kitchen > 10)
print( my_kitchen > 10 and my_kitchen < 18)
print()

# my_kitchen smaller than 14 or bigger than 17?
print( 14< my_kitchen > 17)
print(my_kitchen < 14 or my_kitchen > 17)
print()

# Double my_kitchen smaller than triple your_kitchen?
print(my_kitchen * 2 < your_kitchen * 3)

False
False

True
True

True


##### Question: Guess the answer

In [66]:
print(not(x < 3), not(y > 14 or y > 10), sep='\n')

True
True


In [67]:
True and True

True

In [70]:
not True

False

In [71]:
x = 8
y = 9
not(not(x < 3) and not(y > 14 or y > 10))

False

#### Boolean operators with Numpy

In [72]:
# Create arrays
import numpy as np
my_house = np.array([18.0, 20.0, 10.75, 9.50])
your_house = np.array([14.0, 24.0, 14.25, 9.0])

# my_house greater than 18.5 or smaller than 10
print(np.logical_or(my_house > 18.5 , my_house < 10))

# Both my_house and your_house smaller than 11
print(np.logical_and(my_house < 11 , your_house < 11))

[False  True False  True]
[False False False  True]


#### Question: what will be the answer

In [73]:
area = 10.0
if(area < 9) :
    print("small")
elif(area < 12) :
    print("medium")
else :
    print("large")

medium


#### `if

In [74]:
# Define variables
room = "kit"
area = 14.0

# if statement for room
if room == "kit" :
    print("looking around in the kitchen.")

# if statement for area
if area > 15:
    print('big place!')

looking around in the kitchen.


#### Add else

In [75]:
# Define variables
room = "kit"
area = 14.0

# if-else construct for room
if room == "kit" :
    print("looking around in the kitchen.")
else :
    print("looking around elsewhere.")

# if-else construct for area
if area > 15 :
    print("big place!")
else:
    print("pretty small.")

looking around in the kitchen.
pretty small.


#### Customize further: elif

In [76]:
# Define variables
room = "bed"
area = 14.0

# if-elif-else construct for room
if room == "kit" :
    print("looking around in the kitchen.")
elif room == "bed":
    print("looking around in the bedroom.")
else :
    print("looking around elsewhere.")

# if-elif-else construct for area
if area > 15 :
    print("big place!")
elif area > 10:
    print('medium size, nice!')
else :
    print("pretty small.")

looking around in the bedroom.
medium size, nice!


#### Booolan operator on pandas DataFrame

In [82]:
# Import cars data
import pandas as pd
cars = pd.read_csv('cars.csv', index_col = 0)
print(cars)
print()

# Extract drives_right column as Series: dr
dr = cars['drives_right']

# Use dr to subset cars: sel
sel = cars[dr == True]

# Print sel
print(sel)

     cars_per_cap        country  drives_right
US            809  United States          True
AUS           731      Australia         False
JPN           588          Japan         False
IN             18          India         False
RU            200         Russia          True
MOR            70        Morocco          True
EG             45          Egypt          True

     cars_per_cap        country  drives_right
US            809  United States          True
RU            200         Russia          True
MOR            70        Morocco          True
EG             45          Egypt          True


In [85]:
# Import cars data
import pandas as pd
cars = pd.read_csv('cars.csv', index_col = 0)

# Convert code to a one-liner
sel = cars[cars['drives_right'] == False]

# Print sel
print(sel)

     cars_per_cap    country  drives_right
AUS           731  Australia         False
JPN           588      Japan         False
IN             18      India         False


In [88]:
# Import cars data
import pandas as pd
cars = pd.read_csv('cars.csv', index_col = 0)

# Create car_maniac: observations that have a cars_per_cap over 500
cpc = cars['cars_per_cap'] #--> step -1
many_cars = cpc > 500 # --> step -2
car_maniac = cars[many_cars] # --> step -3

# Print car_maniac
print(car_maniac)

     cars_per_cap        country  drives_right
US            809  United States          True
AUS           731      Australia         False
JPN           588          Japan         False


In [89]:
# Import cars data
import pandas as pd
cars = pd.read_csv('cars.csv', index_col = 0)

# Import numpy, you'll need this
import numpy as np

# Create medium: observations with cars_per_cap between 100 and 500
cpc = cars['cars_per_cap']
between = np.logical_and(cpc < 500, cpc> 100) #double condition
medium = cars[between]


# Print medium
print(medium)

    cars_per_cap country  drives_right
RU           200  Russia          True


In [91]:
cpc = cars['cars_per_cap']
between = np.logical_and(cpc > 10, cpc < 80)
medium = cars[between]
medium

cars_per_cap  country  drives_right
IN             18    India         False
MOR            70  Morocco          True
EG             45    Egypt          True