#### Your First NumPy Array

In [1]:
# Create list baseball
baseball = [180, 215, 210, 210, 188, 176, 209, 200]

# Import the numpy package as np
import numpy as np

# Create a numpy array from baseball: np_baseball
np_baseball = np.array(baseball)

# Print out type of np_baseball
print(np_baseball)
print(type(np_baseball))

[180 215 210 210 188 176 209 200]
<class 'numpy.ndarray'>


In [2]:
# height is available as a regular list
height_in = [73,54,23,67,87,87,98,23,45,65,76]

# Import numpy
import numpy as np

# Create a numpy array from height_in: np_height_in
np_height_in = np.array(height_in)

# Print out np_height_in
print(np_height_in)

# Convert np_height_in to m: np_height_m
np_height_m = np_height_in * 0.0254

# Print np_height_m
print(np_height_m)

[73 54 23 67 87 87 98 23 45 65 76]
[1.8542 1.3716 0.5842 1.7018 2.2098 2.2098 2.4892 0.5842 1.143  1.651
 1.9304]


### Baseball player's BMI

In [3]:
# height and weight are available as regular lists
weight_lb = [180,215,210,210,188,176,209,200,231,180,188]
height_in = [74,75,75,71,71,74,77,71,74,75,77]

# Import numpy
import numpy as np

# Create array from height_in with metric units: np_height_m
np_height_m = np.array(height_in) * 0.0254

# Create array from weight_lb with metric units: np_weight_kg
np_weight_kg = np.array(weight_lb) * 0.453592

# Calculate the BMI: bmi
bmi = np_weight_kg / np_height_m ** 2

# Print out bmi
print(bmi)


[23.11037639 26.87285979 26.24790956 29.28873067 26.22038745 22.59681247
 24.78350857 27.89402921 29.65831637 22.4982082  22.29329957]


#### Lightweight baseball players

In [5]:
# height and weight are available as a regular lists

# Import numpy
import numpy as np

# Calculate the BMI: bmi
np_height_m = np.array(height_in) * 0.0254
np_weight_kg = np.array(weight_lb) * 0.453592
bmi = np_weight_kg / np_height_m ** 2

# Create the light array
light = bmi < 21

# Print out light
print(light)


# Print out BMIs of all baseball players whose BMI is below 21
print(bmi[light])


[False False False False False False False False False False False]
[]


#### Subsetting NumPy Arrays

In [9]:
# height and weight are available as a regular lists

# Import numpy
import numpy as np

# Store weight and height lists as numpy arrays
np_weight_lb = np.array(weight_lb)
np_height_in = np.array(height_in)

# Print out the weight at index 50
print(np_weight_lb[4])

# Print out sub-array of np_height_in: index 100 up to and including index 110
print(np_height_in[2:6])

188
[75 71 71 74]


#### Your First 2D NumPy Array

In [10]:
# Create baseball, a list of lists
baseball = [[180, 78.4],
            [215, 102.7],
            [210, 98.5],
            [188, 75.2]]

# Import numpy
import numpy as np

# Create a 2D numpy array from baseball: np_baseball
np_baseball = np.array(baseball)

# Print out the type of np_baseball
print(type(np_baseball))

# Print out the shape of np_baseball
print(np_baseball.shape)


<class 'numpy.ndarray'>
(4, 2)


### Baseball data in 2D form

In [11]:
# baseball is available as a regular list of lists
baseball = [[74, 180],
            [74, 215],
            [72, 210],
            [72, 210],
            [73, 188],
            [69, 176],
            [69, 209],
            [71, 200],
            [76, 231],
            [71, 180],
            [73, 188],
            [73, 180],
            [74, 185]]

# Import numpy package
import numpy as np

# Create a 2D numpy array from baseball: np_baseball
np_baseball = np.array(baseball)

# Print out the shape of np_baseball
print(np_baseball.shape)

(13, 2)


#### Subsetting 2D NumPy Arrays

In [13]:
# baseball is available as a regular list of lists

# Import numpy package
import numpy as np

# Create np_baseball (2 cols)
np_baseball = np.array(baseball)

# Print out the 50th row of np_baseball
print(np_baseball[49:])

# Select the entire second column of np_baseball: np_weight_lb
np_weight_lb = np_baseball[:,1]

# Print out height of 124th player
print(np_baseball[5][1])


[]
176


#### 2D Arithmetic

In [18]:
# baseball is available as a regular list of lists
baseball = [[74, 180],
            [74, 215],
            [72, 210],
            [72, 210],
            [73, 188],
            [69, 176]]

# updated is available as 2D numpy array
updated = [[  1.2303559 , -11.16224898],
           [  1.02614252,  16.09732309],
           [  1.1544228 ,   5.08167641],
           [  1.09349925,   4.23890778],
           [  0.82285669, -17.78200035],
           [  0.99484223,   8.14402711]]

# Import numpy package
import numpy as np

# Create np_baseball (3 cols)
np_baseball = np.array(baseball)

# Print out addition of np_baseball and updated
print( np_baseball + updated)
print()

# Create numpy array: conversion
conversion = np.array([0.0254, 0.453592])

# Print out product of np_baseball and conversion
print(np_baseball * conversion)


[[ 75.2303559  168.83775102]
 [ 75.02614252 231.09732309]
 [ 73.1544228  215.08167641]
 [ 73.09349925 214.23890778]
 [ 73.82285669 170.21799965]
 [ 69.99484223 184.14402711]]

[[ 1.8796   81.64656 ]
 [ 1.8796   97.52228 ]
 [ 1.8288   95.25432 ]
 [ 1.8288   95.25432 ]
 [ 1.8542   85.275296]
 [ 1.7526   79.832192]]


### Numpy sattistics

#### Average versus median

In [19]:
# np_baseball is available

# Import numpy
import numpy as np

# Create np_height_in from np_baseball
np_height_in = np.array(np_baseball)[:,0]

# Print out the mean of np_height_in
print(np.mean(np_height_in))


# Print out the median of np_height_in
print(np.median(np_height_in))

72.33333333333333
72.5


#### Explore the baseball data

In [20]:
# np_baseball is available

# Import numpy
import numpy as np

# Print mean height (first column)
avg = np.mean(np_baseball[:,0])
print("Average: " + str(avg))

# Print median height. Replace 'None'
med = np.median(np_baseball[:,0])
print("Median: " + str(med))

# Print out the standard deviation on height. Replace 'None'
stddev = np.std(np_baseball[:,0])
print("Standard Deviation: " + str(stddev))

# Print out correlation between first and second column. Replace 'None'
corr = np.corrcoef(np_baseball[:,0],np_baseball[:,1])
print("Correlation: " + str(corr))

Average: 72.33333333333333
Median: 72.5
Standard Deviation: 1.699673171197595
Correlation: [[1.         0.35690586]
 [0.35690586 1.        ]]


#### Blend it all together

In [24]:
# heights and positions are available as lists
heights = [191,184,185,180,181,170]
positions = ['A','M','D','M','D','GK']

# Import numpy
import numpy as np

# Convert positions and heights to numpy arrays: np_positions, np_heights
np_positions = np.array(positions)
np_heights = np.array(heights)

# Heights of the goalkeepers: gk_heights
gk_heights = np_heights[np_positions == 'GK']

# Heights of the other players: other_heights
other_heights = np_heights[np_positions != 'GK']

# Print out the median height of goalkeepers. Replace 'None'
print("Median height of goalkeepers: " + str(np.median(gk_heights)))

# Print out the median height of other players. Replace 'None'
print("Median height of other players: " + str(np.median(other_heights)))

Median height of goalkeepers: 170.0
Median height of other players: 184.0
