# Hello Python...

- How to write & Execute code on [Jupyter Notebook](https://jupyter.org/) a Distribution of [Anaconda](https://www.anaconda.com/)

## Why Python ?

- General purpose: build anything
- Open source! Free!
- Python packages, also for data science
    - Many applications and fields
- Version 3.x - [Download Python](https://www.python.org/downloads/)

### Any Comments?

In [1]:
#  After Using "#" everything in that line will be counted as comment 

### Print or Python as Calculator

In [2]:
# Addition, subtraction
print(5 + 5)
print(5 - 5)

# Multiplication, division, modulo, and exponentiation
print(3 * 5)
print(10 / 2)
print(18 % 7)
print(4 ** 2)

# How much is your $100 worth after 7 years?
print(100*(1.1**7))

10
0
15
5.0
4
16
194.87171000000012


# Variables & Types

## 1- Variables

- Specific, case-sensitive name
- call up values through variable name
- 1.79m - 68.7kg

In [3]:
height = 1.79
weight = 68.7

In [4]:
weight

68.7

### Calculating BMI Using Variables

In [4]:
height = 1.79
weight = 68.7
height

1.79

***BMI = weight / height^2***

In [5]:
68.7 / 1.79 ** 2

21.44127836209856

In [6]:
weight / height ** 2

21.44127836209856

In [7]:
bmi = weight / height ** 2
bmi

21.44127836209856

In [24]:
height = 1.79
weight = 68.7
bmi = weight / height ** 2
print(bmi)

21.44127836209856


### Reproducibility

In [6]:
height = 1.79
weight = 74.2 # <-
bmi = weight / height ** 2
print(bmi)

23.157829031553323


## 2- Python Types 

In [7]:
type(bmi)

float

In [8]:
day_of_week = 5
type(day_of_week)

int

In [9]:
x = "body mass index"
y = 'this works too'
type(y)

str

In [10]:
z = True
type(z)

bool

### Different Behaviours

- Different Types == Different Behaviours

In [17]:
2 + 3

5

In [18]:
'ab' + 'cd'

'abcd'

### Type Conversion

In [16]:
# Definition of savings and result
savings = 100
result = 100 * 1.10 ** 7

# Fix the printout
print("I started with $" + str(savings) + " and now have $" + str(result) + ". Awesome!")

# Definition of pi_string
pi_string = "3.1415926"

# Convert pi_string into float: pi_float
pi_float = float(pi_string)
type(pi_float)
type(str(savings))

I started with $100 and now have $194.87171000000012. Awesome!


str

## Background

Python Data Types

- `float` - real numbers.
- `int` - integer number.
- `str` - string, Text.
- `bool` - True/False.

In [4]:
height = 1.73
tall = True

## Problem

- Each variable represents single value.
- Data Science: Many data points.
- eg: Heights of the Family

In [5]:
height1 = 1.73
height2 = 1.68
height3 = 1.71
height4 = 1.89

- Inconvenient way

# Python List

In [17]:
[1.73, 1.68, 1.71, 1.89]

[1.73, 1.68, 1.71, 1.89]

In [18]:
fam = [1.73, 1.68, 1.71, 1.89]
fam

[1.73, 1.68, 1.71, 1.89]

- Name a collection of values
- Contain any type
- Contain different types

In [20]:
fam = ["liz", 1.73,"emma", 1.68,"mom", 1.71,"dad", 1.89]
fam

['liz', 1.73, 'emma', 1.68, 'mom', 1.71, 'dad', 1.89]

In [21]:
fam2 = [["liz", 1.73],
        ["emma", 1.68],
        ["mom", 1.71],
        ["dad", 1.89]]
fam2

[['liz', 1.73], ['emma', 1.68], ['mom', 1.71], ['dad', 1.89]]

### List type

In [22]:
type(fam)

list

In [23]:
type(fam2)

list

- Specific functionality.
- Specific Behaviour.

### Subsetting Lists

In [24]:
fam = ["liz", 1.73,"emma", 1.68,"mom", 1.71,"dad", 1.89]
fam

['liz', 1.73, 'emma', 1.68, 'mom', 1.71, 'dad', 1.89]

In [25]:
fam[3]

1.68

In [26]:
fam[6]

'dad'

In [19]:
fam[-1] # <-

1.89

In [22]:
fam[7] # <-

1.89

In [23]:
fam[3:5]

[1.68, 'mom']

In [25]:
fam[1:4]

[1.73, 'emma', 1.68]

#### NOTE:
<img src = "./media/list.png">

In [26]:
fam[:4]

['liz', 1.73, 'emma', 1.68]

In [27]:
fam[5:]

[1.71, 'dad', 1.89]

### Manipulating Lists

- Change list elements
- Add list elements
- Remove list elements


#### Changing list elements

In [28]:
fam = ["liz", 1.73,"emma", 1.68,"mom", 1.71,"dad", 1.89]
fam

['liz', 1.73, 'emma', 1.68, 'mom', 1.71, 'dad', 1.89]

In [29]:
fam[7] = 1.86
fam

['liz', 1.73, 'emma', 1.68, 'mom', 1.71, 'dad', 1.86]

In [31]:
fam[0:2] = ["lisa", 1.74]
fam

['lisa', 1.74, 'emma', 1.68, 'mom', 1.71, 'dad', 1.86]

### Adding and removing elements

In [32]:
fam + ["me", 1.79]

['lisa', 1.74, 'emma', 1.68, 'mom', 1.71, 'dad', 1.86, 'me', 1.79]

In [33]:
fam_ext = fam + ["me", 1.79]
del(fam[2])
fam

['lisa', 1.74, 1.68, 'mom', 1.71, 'dad', 1.86]

### Behind the scenes (1)

In [34]:
x = ["a","b","c"]

<img src= "./media/bh1.png" >

In [36]:
x = ["a","b","c"]
y = x
y[1] = "z"
y

['a', 'z', 'c']

In [37]:
x

['a', 'z', 'c']

<img src = "./media/b3.png">

In [47]:
x = ["a","b","c"]
y = list(x)
y = x[:]
y[1] = "z"
y

['a', 'z', 'c']

In [48]:
x

['a', 'b', 'c']

<img src = "./media/bh4.png">

# Functions

- Nothing new!
- `type()`
- Piece of reusable code
- Solves particular task
- Call function instead of writing code yourself
- eg: family heights


In [49]:
fam = [1.73, 1.68, 1.71, 1.89]
fam

[1.73, 1.68, 1.71, 1.89]

In [50]:
max(fam)

1.89

<img src = "./media/functions_BehindScenes.png">

In [51]:
tallest = max(fam)
tallest

1.89

### round()

In [52]:
round(1.68, 1)

1.7

In [53]:
round(1.68)

2

In [54]:
help(round) # Open up documentation

Help on built-in function round in module builtins:

round(number, ndigits=None)
    Round a number to a given precision in decimal digits.
    
    The return value is an integer if ndigits is omitted or None.  Otherwise
    the return value has the same type as the number.  ndigits may be negative.



- `round(number)`
- `round(number, ndigits)`

<img src = "./media/functions_BehindScenes_round.png">

<img src = "./media/functions_BehindScenes_round2.png">

### Find functions
- How to know?
- Standard task -> probably function exists!
- The internet is your friend

# Problem

- Maximum of list: `max()`
- Length of list or string: `len()`
- Get index in list: `?`
- Reversing a list: `?`

# Solution: Methods
 
- method or used to apply any operation on specific object.

<img src = './media/method.png' width = 600 height = 600>

In [56]:
fam = ["liz", 1.73,"emma", 1.68,"mom", 1.71,"dad", 1.89]
fam

['liz', 1.73, 'emma', 1.68, 'mom', 1.71, 'dad', 1.89]

### list methods

In [57]:
fam.index("mom") # "Call method index() on fam"

4

In [59]:
fam.count(1.73)

1

### str methods

In [62]:
sister = 'Liz'
sister

'Liz'

In [63]:
sister.capitalize()

'Liz'

In [64]:
sister.replace("z","sa")

'Lisa'

### Methods
- Everything = object
- Object have methods associated, depending on type

In [67]:
fam.replace("mom","mommy")

AttributeError: 'list' object has no attribute 'replace'

In [68]:
sister.index("z")

2

In [69]:
fam.append("me")
fam

['liz', 1.73, 'emma', 1.68, 'mom', 1.71, 'dad', 1.89, 'me']

In [70]:
fam.append(1.79)
fam

['liz', 1.73, 'emma', 1.68, 'mom', 1.71, 'dad', 1.89, 'me', 1.79]

### Summary

- `Functions`: call directly

In [72]:
type(fam)

list

- `Methods`: call functions on objects

In [73]:
fam.index("dad")

6

#  Background "OR" Motivation

- Functions and methods are powerful
- All code in Python distribution?
- Huge code base: messy
- Lots of code you won’t use
- Maintenance problem

# Result : Packages

- Directory of Python Scripts
- ***Each script = module***
- Specify functions, methods,types
- Thousands of packages available
    - `Numpy`
    - `Matplotlib`
    - `Scikit-learn`

<img src = "./media/module.png">

### Install package
- Download `get-pip.py`
- Terminal:
    - `python3 get-pip.py`
    - `pip3 install numpy`


### Import package

In [74]:
import numpy
array([1, 2, 3])

NameError: name 'array' is not defined

In [75]:
numpy.array([1, 2, 3])

array([1, 2, 3])

In [76]:
import numpy as np
np.array([1, 2, 3])

array([1, 2, 3])

In [77]:
from numpy import array
array([1, 2, 3])

array([1, 2, 3])

- ***Below I'm Using Numpy, but not very clear***

In [79]:
from numpy import array

fam = ["liz", 1.73,"emma", 1.68,"mom", 1.71,"dad", 1.89]

fam_ext = fam + ["me", 1.79]

print(str(len(fam_ext)) + " elements in fam_ext")

np_fam = array(fam_ext)
print(np_fam)

10 elements in fam_ext
['liz' '1.73' 'emma' '1.68' 'mom' '1.71' 'dad' '1.89' 'me' '1.79']


- ***Recomended method to import & use packages***

In [80]:
import numpy as np

fam = ["liz", 1.73,"emma", 1.68,"mom", 1.71,"dad", 1.89]

fam_ext = fam + ["me", 1.79]

print(str(len(fam_ext)) + " elements in fam_ext")

np_fam = np.array(fam_ext)
print(np_fam)

10 elements in fam_ext
['liz' '1.73' 'emma' '1.68' 'mom' '1.71' 'dad' '1.89' 'me' '1.79']


# Numpy

### Lists Recap
- Powerful
- Collection of values
- Hold different types
- change, add, remove.
- Need for Data Sciecne.
    - Mathematical operations over collections
    - Speed

### Illustration

In [81]:
height = [1.73, 1.68, 1.71, 1.89, 1.79]
height

[1.73, 1.68, 1.71, 1.89, 1.79]

In [82]:
weight = [65.4, 59.2, 63.6, 88.4, 68.7]
weight

[65.4, 59.2, 63.6, 88.4, 68.7]

In [83]:
weight / height ** 2

TypeError: unsupported operand type(s) for ** or pow(): 'list' and 'int'

### Solution: Numpy

- Numeric Python
- Alternative to Python List: Numpy Array
- Calculations over entire arrays
- Easy and Fast
- Installation
- In the terminal: `pip3 install numpy`


### Numpy

In [84]:
import numpy as np
np_height = np.array(height)
np_height

array([1.73, 1.68, 1.71, 1.89, 1.79])

In [85]:
np_weight = np.array(weight)
np_weight

array([65.4, 59.2, 63.6, 88.4, 68.7])

In [86]:
bmi = np_weight / np_height ** 2
bmi

array([21.85171573, 20.97505669, 21.75028214, 24.7473475 , 21.44127836])

#### Comparison

In [87]:
height = [1.73, 1.68, 1.71, 1.89, 1.79]
weight = [65.4, 59.2, 63.6, 88.4, 68.7]
weight / height ** 2

TypeError: unsupported operand type(s) for ** or pow(): 'list' and 'int'

In [88]:
np_height = np.array(height)
np_weight = np.array(weight)
np_weight / np_height ** 2

array([21.85171573, 20.97505669, 21.75028214, 24.7473475 , 21.44127836])

### Numpy: remarks

In [89]:
np.array([1.0,"is", True])

array(['1.0', 'is', 'True'], dtype='<U32')

- Numpy arrays: ***contain only one type***

In [90]:
python_list = [1, 2, 3]
numpy_array = np.array([1, 2, 3])

In [91]:
python_list + python_list

[1, 2, 3, 1, 2, 3]

In [92]:
numpy_array + numpy_array

array([2, 4, 6])

***NOTE : Different Types = Different Behaviour***

### Numpy Subsetting

In [93]:
bmi

array([21.85171573, 20.97505669, 21.75028214, 24.7473475 , 21.44127836])

In [94]:
bmi[3]

24.74734749867025

In [95]:
bmi > 23

array([False, False, False,  True, False])

In [96]:
bmi[bmi > 23]

array([24.7473475])

### Type of Numpy Arrays

In [97]:
import numpy as np
np_height = np.array([1.73, 1.68, 1.71, 1.89, 1.79])
np_weight = np.array([65.4, 59.2, 63.6, 88.4, 68.7])

In [98]:
type(np_height)

numpy.ndarray

In [100]:
type(np_weight)

numpy.ndarray

### 2D Numpy Arrays

In [101]:
np_2d = np.array([[1.73, 1.68, 1.71, 1.89, 1.79],
                  [65.4, 59.2, 63.6, 88.4, 68.7]])
np_2d

array([[ 1.73,  1.68,  1.71,  1.89,  1.79],
       [65.4 , 59.2 , 63.6 , 88.4 , 68.7 ]])

In [103]:
np_2d.shape # 2 rows , 5 columns

(2, 5)

In [104]:
np.array([[1.73, 1.68, 1.71, 1.89, 1.79],
          [65.4, 59.2, 63.6, 88.4,"68.7"]])

array([['1.73', '1.68', '1.71', '1.89', '1.79'],
       ['65.4', '59.2', '63.6', '88.4', '68.7']], dtype='<U32')

### Subsetting

In [105]:
np_2d[0]

array([1.73, 1.68, 1.71, 1.89, 1.79])

In [106]:
np_2d[0][2]

1.71

In [107]:
np_2d[0,2]

1.71

In [108]:
np_2d[:,1:3]

array([[ 1.68,  1.71],
       [59.2 , 63.6 ]])

In [109]:
np_2d[1,:]

array([65.4, 59.2, 63.6, 88.4, 68.7])

### Numpy: Basic Statistics

- In **Data analysis we have to Get to know your data***
    - Little data -> ***Simply look at it***
    - Big data - > ?

In [116]:
np.mean(np_city[:,0])

1.747842

In [117]:
np.median(np_city[:,0])

1.75

In [118]:
np.corrcoef(np_city[:,0], np_city[:,1])

array([[1.        , 0.02078428],
       [0.02078428, 1.        ]])

In [119]:
np.std(np_city[:,0])

0.19973292927306704

- `sum()`, `sort()`, ...
- Enforce single data type: speed!


### Generate data
- Arguments for `np.random.normal()`
    - distribution mean
    - distribution standard deviation
    - number of samples

In [110]:
height = np.round(np.random.normal(1.75, 0.20, 5000), 2)

In [111]:
height

array([1.75, 1.79, 1.81, ..., 1.63, 1.95, 1.63])

In [112]:
weight = np.round(np.random.normal(60.32, 15, 5000), 2)

In [113]:
weight

array([78.77, 62.72, 44.98, ..., 67.96, 70.05, 60.72])

In [114]:
np_city = np.column_stack((height, weight))

In [115]:
np_city

array([[ 1.75, 78.77],
       [ 1.79, 62.72],
       [ 1.81, 44.98],
       ...,
       [ 1.63, 67.96],
       [ 1.95, 70.05],
       [ 1.63, 60.72]])

In [3]:
import numpy as np
array_1 = np.array([[1, 2, 7], [3, 4, 8]])
array_2 = np.array([[1, 2], [3, 9], [4, 16]])

In [4]:
np.dot(array_1, array_2)

array([[ 35, 132],
       [ 47, 170]])

In [5]:
for i in [0,2,3]:
    if i%2 == 0:
        print("even")
    elif i == 0:
        print("zero")
    else:
        print("odd")

even
even
odd
